services:
  nextjs-app:
    container_name: study-english
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3020:3000'
    env_file:
      - .env
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
    restart: unless-stopped
